package com.ahmetyildiz.quakealert.core.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Brand colour schemes. Light values are the design system's; dark values come from the same Material 3 "fidelity"
// tonal palettes (primary #006874, secondary #4A6267, tertiary #785900, neutral #70787D), so both themes stay in sync.
// surfaceVariant equals surfaceContainerHighest, as in the design system.

internal val LightColorScheme: ColorScheme = lightColorScheme(
    primary = Color(0xFF004E58),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF006874),
    onPrimaryContainer = Color(0xFF97E4F2),
    inversePrimary = Color(0xFF85D2E0),
    secondary = Color(0xFF4A6267),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCDE7ED),
    onSecondaryContainer = Color(0xFF50686D),
    tertiary = Color(0xFF5B4200),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF785900),
    onTertiaryContainer = Color(0xFFFDD275),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFF4FAFF),
    onBackground = Color(0xFF151D21),
    surface = Color(0xFFF4FAFF),
    onSurface = Color(0xFF151D21),
    surfaceVariant = Color(0xFFDCE4E9),
    onSurfaceVariant = Color(0xFF3F484A),
    surfaceTint = Color(0xFF016874),
    inverseSurface = Color(0xFF2A3136),
    inverseOnSurface = Color(0xFFEAF2F7),
    outline = Color(0xFF6F797B),
    outlineVariant = Color(0xFFBEC8CA),
    surfaceBright = Color(0xFFF4FAFF),
    surfaceDim = Color(0xFFD3DBE1),
    surfaceContainer = Color(0xFFE7EFF5),
    surfaceContainerHigh = Color(0xFFE1E9EF),
    surfaceContainerHighest = Color(0xFFDCE4E9),
    surfaceContainerLow = Color(0xFFEDF5FA),
    surfaceContainerLowest = Color(0xFFFFFFFF),
)

internal val DarkColorScheme: ColorScheme = darkColorScheme(
    primary = Color(0xFF85D2E0),
    onPrimary = Color(0xFF00363D),
    primaryContainer = Color(0xFF006874),
    onPrimaryContainer = Color(0xFF97E4F2),
    inversePrimary = Color(0xFF016874),
    secondary = Color(0xFFB1CBD1),
    onSecondary = Color(0xFF1C3439),
    secondaryContainer = Color(0xFF354D52),
    onSecondaryContainer = Color(0xFFA3BDC2),
    tertiary = Color(0xFFEBC166),
    onTertiary = Color(0xFF3F2E00),
    tertiaryContainer = Color(0xFF785900),
    onTertiaryContainer = Color(0xFFFDD275),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF0D1418),
    onBackground = Color(0xFFDCE4E9),
    surface = Color(0xFF0D1418),
    onSurface = Color(0xFFDCE4E9),
    surfaceVariant = Color(0xFF2E363A),
    onSurfaceVariant = Color(0xFFBEC8CA),
    surfaceTint = Color(0xFF85D2E0),
    inverseSurface = Color(0xFFDCE4E9),
    inverseOnSurface = Color(0xFF2A3136),
    outline = Color(0xFF889294),
    outlineVariant = Color(0xFF3F484A),
    surfaceBright = Color(0xFF323A3F),
    surfaceDim = Color(0xFF0D1418),
    surfaceContainer = Color(0xFF192125),
    surfaceContainerHigh = Color(0xFF232B2F),
    surfaceContainerHighest = Color(0xFF2E363A),
    surfaceContainerLow = Color(0xFF151D21),
    surfaceContainerLowest = Color(0xFF080F13),
)
